analyzer_rules:
  - unused_declaration
  - unused_import

opt_in_rules:
  - anonymous_argument_in_multiline_closure
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - fallthrough
  - file_name
  - file_name_no_space
  - first_where
  - identical_operands
  - missing_docs
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - prefer_zero_over_explicit_init
  - sorted_imports
  - sorted_first_last
  - static_operator
  - toggle_bool
  - type_contents_order
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

excluded:
  - BitwardenShared/Application/Support/Generated

cyclomatic_complexity:
  ignores_case_statements: true

multiline_arguments:
  only_enforce_after_first_closure_on_first_line: true

trailing_comma:
  mandatory_comma: true

type_contents_order:
  order:
    - case
    - type_alias
    - associated_type
    - subtype
    - type_property
    - instance_property
    - ib_inspectable
    - ib_outlet
    - initializer
    - deinitializer
    - type_method
    - view_life_cycle_method
    - ib_action
    - other_method
    - subscript

identifier_name:
  excluded:
    - id
