---
name: Cache Dependencies

on:
  push:
    branches:
      - main

env:
  DEVELOPER_DIR: /Applications/Xcode_15.0.1.app/Contents/Developer
  MINT_LINK_PATH: .mint/bin
  MINT_PATH: .mint/lib

jobs:
  cache-dependencies:
    name: Cache Dependencies
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Ruby
        uses: ruby/setup-ruby@af848b40be8bb463a751551a1180d74782ba8a72 # v1.162.0
        with:
          bundler-cache: true
          ruby-version: 3.2.2

      - name: Cache Mint Packages
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          path: .mint
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: |
            ${{ runner.os }}-mint-

      - name: Cache SPM Packages
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          path: build/DerivedData/SourcePackages
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Setup
        run: |
          brew install mint xcbeautify
          ./Scripts/bootstrap.sh

      - name: Update Xcode Dependencies
        run: |
          set -o pipefail && \
            xcodebuild -resolvePackageDependencies \
            -project Bitwarden.xcodeproj \
            -clonedSourcePackagesDirPath build/DerivedData/SourcePackages
