name: Cache

on:
  push:
    branches:
      - "main"

env:
  DEVELOPER_DIR: /Applications/Xcode_15.0.1.app/Contents/Developer
  MINT_LINK_PATH: .mint/bin
  MINT_PATH: .mint/lib

jobs:
  cache-dependencies:
    name: Cache dependencies
    runs-on: macos-14
    steps:
      - name: Check out repo
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Configure Ruby
        uses: ruby/setup-ruby@0cde4689ba33c09f1b890c1725572ad96751a3fc # v1.178.0
        with:
          bundler-cache: true

      - name: Cache Mint packages
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: .mint
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: |
            ${{ runner.os }}-mint-

      - name: Cache SPM packages
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: build/DerivedData/SourcePackages
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Install Mint and xcbeautify
        run: |
          brew install mint xcbeautify
          ./Scripts/bootstrap.sh

      - name: Update Xcode dependencies
        run: |
          set -o pipefail && \
            xcodebuild -resolvePackageDependencies \
            -project Bitwarden.xcodeproj \
            -clonedSourcePackagesDirPath build/DerivedData/SourcePackages
