---
name: Test

on:
  pull_request:

env:
  DEVELOPER_DIR: /Applications/Xcode_14.3.1.app/Contents/Developer
  MINT_LINK_PATH: .mint/bin
  MINT_PATH: .mint/lib
  SIMULATOR_DESTINATION: platform=iOS Simulator,name=iPhone 14 Pro,OS=16.4

jobs:
  test:
    name: Test
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Ruby
        uses: ruby/setup-ruby@54a18e26dbbb1eabc604f317ade9a5788dddef81 # v1.159.0
        with:
          bundler-cache: true
          ruby-version: 3.2.2

      - name: Cache Mint Packages
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          path: .mint
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: |
            ${{ runner.os }}-mint-

      - name: Cache SPM Packages
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          path: build/DerivedData/SourcePackages
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Setup
        run: |
          brew install mint xcbeautify
          ./Scripts/bootstrap.sh

      - name: Build and Test
        run: |
          set -o pipefail && \
            xcodebuild test \
            -project Bitwarden.xcodeproj \
            -scheme Bitwarden \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination "${{ env.SIMULATOR_DESTINATION }}" \
            -resultBundlePath build/BitwardenTests.xcresult \
            -derivedDataPath build/DerivedData \
            | xcbeautify --renderer github-actions

      - name: Danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bundle exec danger
