name: Test

on:
  push:
    branches:
      - "main"
      - "rc"
      - "hotfix-rc"
  pull_request_target:
    types: [opened, synchronize]

env:
  DEVELOPER_DIR: /Applications/Xcode_15.0.1.app/Contents/Developer
  MINT_LINK_PATH: .mint/bin
  MINT_PATH: .mint/lib
  SIMULATOR_DESTINATION: platform=iOS Simulator,name=iPhone 15 Pro,OS=17.0.1

jobs:
  check-run:
    name: Check PR run
    uses: bitwarden/gh-actions/.github/workflows/check-run.yml@main

  test:
    name: Test
    runs-on: macos-14-xlarge
    needs: check-run
    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - name: Check out repo
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          ref: ${{  github.event.pull_request.head.sha }}

      - name: Configure Ruby
        uses: ruby/setup-ruby@943103cae7d3f1bb1e4951d5fcc7928b40e4b742 # v1.177.1
        with:
          bundler-cache: true

      - name: Cache Mint packages
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: .mint
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: |
            ${{ runner.os }}-mint-

      - name: Cache SPM packages
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: build/DerivedData/SourcePackages
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Install yeetd
        run: |
          wget https://github.com/biscuitehh/yeetd/releases/download/1.0/yeetd-normal.pkg
          sudo installer -pkg yeetd-normal.pkg -target /
          yeetd &

      - name: Install Mint and xcbeautify
        run: |
          brew install mint xcbeautify
          ./Scripts/bootstrap.sh

      - name: Build and test
        run: |
          set -o pipefail && \
            xcodebuild test \
            -project Bitwarden.xcodeproj \
            -scheme Bitwarden \
            -configuration Debug \
            -destination "${{ env.SIMULATOR_DESTINATION }}" \
            -resultBundlePath build/BitwardenTests.xcresult \
            -derivedDataPath build/DerivedData \
            | xcbeautify --renderer github-actions

      - name: Danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bundle exec danger
